### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by DiederikvandenB** [myMartek/stream-deck-fs-symbols-icons#1]
Hi, thanks for providing this plugin.

I am missing some icons, such as these:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/6132723/163382754-88bf8210-bd89-48c6-bcb9-47396008f72d.png">

Could these be added? Cheers!

**Comment by myMartek** [comment]
I added those to the end of the list. An update in Elgatos store should be live soon.
